export { ForeignLeadSchema, LeadSchema, type ForeignLead, type Lead } from "./lead";
export { DATA_POLICY_SLUG, LEGAL_DOCUMENTS, type LegalDocumentRef } from "./legal";
export { PQR_TYPE_LABELS, PQR_TYPES, PqrSchema, type Pqr, type PqrType } from "./pqr";
export type {
  Amenity,
  AmenityIconKey,
  CalculatorConfig,
  City,
  ConstructionStatus,
  ExchangeRate,
  Faq,
  FaqBotPublicConfig,
  ForeignBuyerPage,
  Geo,
  HomeBanner,
  HomePage,
  LeadFormConfig,
  LegalDocument,
  Macroproject,
  Media,
  PointOfInterest,
  Post,
  PostCategory,
  Project,
  Redirect,
  Seo,
  Stage,
  ToolIconKey,
  UnitType,
} from "./content-types";
