export {
  ExternalLeadSchema,
  ForeignLeadSchema,
  ForeignLeadSubmissionSchema,
  inferLeadForm,
  LEAD_FORM_LABELS,
  LEAD_FORMS,
  LeadSchema,
  LeadSubmissionSchema,
  type ForeignLead,
  type Lead,
  type LeadFormId,
  type LeadSubmission,
} from "./lead";
export {
  FOOTER_DEFAULTS,
  FOOTER_SOCIAL_NETWORKS,
  type Footer,
  type FooterLink,
  type FooterSocialNetwork,
} from "./footer";
export { DATA_POLICY_SLUG, LEGAL_DOCUMENTS, type LegalDocumentRef } from "./legal";
export { PQR_TYPE_LABELS, PQR_TYPES, PqrSchema, type Pqr, type PqrType } from "./pqr";
export type {
  Amenity,
  AmenityIconKey,
  CalculatorConfig,
  City,
  ConstructionStatus,
  ExchangeRate,
  Faq,
  FaqTopic,
  FaqBotPublicConfig,
  ForeignBuyerPage,
  Geo,
  HomeBanner,
  Launch,
  HomePage,
  LeadFormConfig,
  LegalDocument,
  Media,
  Post,
  PostCategory,
  PqrPage,
  CustomerServicePage,
  Project,
  Redirect,
  Seo,
  Stage,
  ToolIconKey,
  UnitType,
} from "./content-types";
